application: quiklyrics
version: 1
runtime: python27
threadsafe: no
api_version: 1

# builtins:
# - datastore_admin: on

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: images/robots.txt
  upload: images/robots.txt

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /images/
  static_dir: images/

- url: /css/
  static_dir: css/

- url: /.*
  script: helloworld.py

